services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"