services:
  session-service:
    build:
      context: ./session-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      # OpenTelemetry
      - NODE_OPTIONS=--require @opentelemetry/auto-instrumentations-node/register
      - OTEL_SERVICE_NAME=session-service
      - OTEL_NODE_DISABLED_INSTRUMENTATIONS="fs" # Produces too many spans
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8081:8081"
    depends_on:
      - redis

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/products
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SESSION_SERVICE_HOST=session-service
      # OpenTelemetry
      - JAVA_TOOL_OPTIONS=-javaagent:/app/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"