services:
  session-service:
    build:
      context: ./session-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      # OpenTelemetry
      - NODE_OPTIONS=--require @opentelemetry/auto-instrumentations-node/register
      - OTEL_SERVICE_NAME=session-service
      - OTEL_NODE_DISABLED_INSTRUMENTATIONS=fs # Produces too many spans
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8081:8081"
    depends_on:
      - redis
