services:
  session-service:
    build:
      context: ./session-service-java
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      # OpenTelemetry
      - JAVA_TOOL_OPTIONS=-javaagent:/app/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8081:8081"
    depends_on:
      - redis
