services:
  autoinstrumenter:
    image: grafana/beyla:latest
    pid: "service:k6"
    privileged: true
    environment:
      #BEYLA_TRACE_PRINTER: text
      BEYLA_OPEN_PORT: 5665
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
    depends_on:
      k6:
        condition: service_started

  # K6 web dashboard available at http://localhost:5665
  k6:
    image: grafana/k6:0.53.0
    volumes:
      - ./k6:/home/k6
    environment:
      # Change this to the URL of the application you want to test
      - PRODUCT_SERVICE=http://product-service:8080
      - SESSION_SERVICE=http://session-service:8081
      # K6 configuration
      - K6_WEB_DASHBOARD=true
      - K6_WEB_DASHBOARD_PERIOD=1s
      - K6_WEB_DASHBOARD_EXPORT=/home/k6/reports/report.html
    ports:
      - "5665:5665"
    #command: [ "run", "--out", "csv=/home/k6/reports/summary.csv", "/home/k6/product.js" ]
    command: [ "run", "/home/k6/product.js" ]
    # when done rename report
    depends_on:
      product-service:
        condition: service_started
      session-service:
        condition: service_started