services:
  # Observability
  collector:
    image: otel/opentelemetry-collector-contrib:0.109.0
    volumes:
      - ./docker/collector/collector-config.yaml:/etc/collector-config.yaml
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: [ "--config=/etc/collector-config.yaml", "--feature-gates=receiver.hostmetrics.normalizeProcessCPUUtilization" ]
    privileged: true
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      grafana:
        condition: service_started
      clickhouse:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native interface
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'localhost:8123/ping' ]
      start_interval: 1s
      start_period: 30s
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DATABASE=otel

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      -  GF_LOG_FILTERS=rendering:debug
    volumes: # Grafana provisioning
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      clickhouse:
        condition: service_healthy

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "3001:8081"