{
 "title": "Benchmark Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "grafana-clickhouse-datasource" },
   { "name": "db", "query": "SHOW DATABASES;" },
   { "name": "cores", "label": "Cores", "query": "32" }
  ]
 },
 "panels": [
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(TimeUnix) as \"time\", ResourceAttributes['container.name'], max(Value) / (${cores}*100) as Utilization FROM \"${db}\".\"otel_metrics_gauge\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( MetricName = 'container.cpu.utilization' ) GROUP BY ResourceAttributes['container.name'], time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(TimeUnix) as \"time\", ResourceAttributes['container.name'], max(Value) as Memory FROM \"${db}\".\"otel_metrics_sum\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( MetricName = 'container.memory.usage.total' ) GROUP BY ResourceAttributes['container.name'], time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Spans produced per ${__interval}",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as \"time\", ServiceName, SpanName, count() FROM \"default\".\"otel_traces\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY ServiceName, SpanName, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Max Client Latency per ${__interval}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as \"time\", SpanAttributes['htt.request.method'], SpanAttributes['url.full'], ServiceName, max(Duration) FROM \"default\".\"otel_traces\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY SpanAttributes['htt.request.method'], SpanAttributes['url.full'], ServiceName, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Client Latency & Session Service Latency per ${__interval}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as \"time\", ServiceName, SpanAttributes['url.full'], avg(Duration), max(Duration) FROM \"default\".\"otel_traces\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( SpanName = 'GET' ) GROUP BY ServiceName, SpanAttributes['url.full'], time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT ServiceName, SpanAttributes['url.full'] as URL, SpanAttributes['http.request.method'] as Method, SpanAttributes['http.response.status_code'] as Status,\r\navg(Duration) AS Average,\r\nquantileExact(0.50)(Duration) as p50,\r\nquantileExact(0.90)(Duration) as p90,\r\nquantileExact(0.95)(Duration) as p95,\r\nquantileExact(0.99)(Duration) as p99,\r\nmax(Duration) as Max,\r\ncount() as Count\r\nFROM ${db}.otel_traces\r\nWHERE SpanAttributes['url.full'] != ''\r\nAND $__timeFilter(Timestamp)\r\nGROUP BY ServiceName, SpanAttributes['http.request.method'], SpanAttributes['url.full'], SpanAttributes['http.response.status_code']"
    }
   ]
  }
 ]
}